# @host = http://localhost:3001
@service-prefix = user-service
@host = http://172.212.52.159


# @name get-users
GET {{host}}/{{service-prefix}}/users

###

# @name get-user-by-id
GET {{host}}/{{service-prefix}}/users/e60aa068-9ace-44a6-a0c8-1f310c709397

###

# @name edit-user
PUT {{host}}/{{service-prefix}}/users/dce1cf4a-aa2a-4b20-9a16-abd36ab7fb72
content-type: application/json


{
    "email": "john.23@gmail.com",
    "name": "John Doe ALTERED"
}


